name: Latest SMY blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: smy/blog-post-workflow@master
        with:
          comment_tag_name: "christopher3810"
          feed_list: "https://colevelup.tistory.com/rss"
          commit_message: "Update smy blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}